# Generated by Django 2.0.5 on 2018-05-03 03:20

import data_visualization.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataByCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('data', djongo.models.fields.ArrayModelField(model_container=data_visualization.models.EthnicityData)),
                ('total', djongo.models.fields.EmbeddedModelField(model_container=data_visualization.models.GenderData, null=True)),
                ('university_total', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EthnicityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=50)),
                ('men', models.IntegerField()),
                ('women', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.IntegerField()),
                ('women', models.IntegerField()),
            ],
        ),
    ]
