# Generated by Django 2.0.5 on 2018-05-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databycollege',
            old_name='classification',
            new_name='college_code',
        ),
        migrations.RenameField(
            model_name='databycollege',
            old_name='date',
            new_name='term',
        ),
    ]
