# Generated by Django 2.0.5 on 2018-05-12 18:40

import datetime
from django.db import migrations
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0002_auto_20180506_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databycollege',
            name='id',
        ),
        migrations.AddField(
            model_name='databycollege',
            name='_id',
            field=djongo.models.fields.ObjectIdField(default=datetime.datetime(2018, 5, 12, 18, 40, 25, 534458, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
